### ISSUE TITLE
Initial Definition for Experiment 3

### ISSUE THREAD

**Issue by kris701** [jamadaha/P6#102]
For instance, in the IMDB data, COUNT(keyword.id=335) is 72496

Nothing is gained from splitting this into many buckets, may as well just let óne bucket contain them all.

Potential solution: When a bucket is made, when it's full, look at the top value, anything following if it's equal.

**Comment by jamadaha** [comment]
Potentially make milestone histograms.
Make very imprecise (Takes less storage) of potential intermiediate results, which can be used in cardinality result estimation. Say that there is a histogram for a > 50 and a < 100, and a query comes up for a > 75 and a < 100, then via the use of the earlier histogram (and possibly variance), an estimate can be created for the query

**Comment by HGinnerup** [comment]
https://docs.google.com/document/d/1sTH_GFK-LpaKRjBM2GBYPDpUNPO3oNkhtTkPjiJjM0k/edit
