### ISSUE TITLE
Make our JanDB to test on

### ISSUE THREAD

**Issue by kris701** [jamadaha/P6#98]

**Comment by kris701** [comment]
Find a more "realistic" dataset and queries. One with a lot of numbers, maybe even some reasonable queries to go with it.

**Comment by HGinnerup** [comment]
https://www.kaggle.com/datasets/fedesoriano/stellar-classification-dataset-sdss17
https://www.kaggle.com/datasets/majyhain/height-of-male-and-female-by-country-2022








Krav:
	Åben licens
	500-100k rækker (Kan selv limit)
	Ikke politisk
	Minimalt meme level
	Forskellige distributioner
		Lige
		Højreskæv
		Venstreskæv
			https://www.kaggle.com/datasets/pralabhpoudel/alcohol-consumption-by-country
		Bellcurve
			https://www.kaggle.com/datasets/mathurinache/world-happiness-report-2022
				Compare various 
		Negative bell curve
		"hullet"
			https://www.kaggle.com/datasets/nasa/kepler-exoplanet-search-results
				koi_score
	
		Stort antal rækker
		Lille antal rækker
	

https://www.kaggle.com/datasets/timmofeyy/-world-metro?select=metro_countries_total.csv
	Venstreskæv, højreskæv


Lille dataset + negativ bell curve
	https://www.kaggle.com/datasets/timmofeyy/-pizza-prices-menu-in-13-different-pizzerias










https://www.kaggle.com/datasets/iabhishekofficial/mobile-price-classification
